# Build by running "snapcraft".

# WARNING:
# Snapcraft uses caching for already build steps but it's buggy and can cause strange problems.
# Clean the cache by running "snapcraft clean".

name: video-downloader
license: GPL-3.0+
grade: stable
adopt-info: video-downloader

base: core22
confinement: strict

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages

apps:
  video-downloader:
    command: usr/bin/video-downloader
    extensions:
      # HINT: Adds plugs and changes environment variables when building and running
      - gnome
    plugs:
      - home
      - network
    common-id: com.github.unrud.VideoDownloader
    desktop: usr/share/applications/com.github.unrud.VideoDownloader.desktop

slots:
  video-downloader:
    interface: dbus
    bus: session
    name: com.github.unrud.VideoDownloader

parts:
  ffmpeg:
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include

  yt-dlp:
    # Missing optional dependencies atomicparsley, mpv, phantomjs and rtmpdump
    after: [ffmpeg]
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.tar.gz
    source-checksum: sha256/6d2115b84b6c11867f92cf4c23705b536bfa0ba9d538b1885f52da6756f8c980
    python-packages:
      - pyxattr==0.7.2
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    override-pull: |
      craftctl default
      sed -i 's/^certifi\b/#\0/' requirements.txt
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg

  video-downloader:
    after: [ffmpeg, yt-dlp]
    plugin: meson
    source: .
    source-type: git
    # WORKAROUND: Fake installation location to find dependencies at runtime
    meson-parameters: [--prefix=/snap/video-downloader/current/usr]
    build-packages:
      - gettext
      - appstream
      - librsvg2-bin
    stage-packages:
      - xdg-user-dirs
    override-pull: |
      craftctl default
      # WORKAROUND: Point icon directly to SVG otherwise snapcraft can't find it
      sed -e 's|Icon=com.github.unrud.VideoDownloader|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.unrud.VideoDownloader.svg|' -i data/com.github.unrud.VideoDownloader.desktop.in
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/video-downloader/current/usr/bin/video-downloader"
    organize:
      # WORKAROUND: Move files from fake installation location to actual target
      snap/video-downloader/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.unrud.VideoDownloader.metainfo.xml]
